### ISSUE TITLE
add :GhcModType, :GhcModTypeClear like functionality

### ISSUE THREAD

**Issue by BjornMelgaard** [FrigoEU/psc-ide-vim#112]
to show not only type of one function under cursor, but [type of expression](https://github.com/eagletmt/ghcmod-vim#ghcmodtype-ghcmodtypeclear)

**Comment by kRITZCREEK** [comment]
That is not supported by purs ide at this point in time and is basically impossible to implement on the editor side, so it shouldn't be tracked here. It's something I have in mind for the purs ide project, but there are a lot of prerequisits missing.

**Comment by BjornMelgaard** [comment]
@kRITZCREEK can you tell what prerequisites are missing? I'm just curious)

**Comment by kRITZCREEK** [comment]
- We need to be able to run the individual parts of the compiler pipeline until we get to the type checker. 
- We need to figure out how to effectively cache some of that work, so that things continue to work eventhough you made a change to an unrelated definition and the module doesn't compile anymore. 
- Depending on how fast or slot that approach is, we might need to track all dependencies between expressions ourselves and only recompile that part of the program which the selected expression depends on.
