### ISSUE TITLE
Path not match for apply suggestion

### ISSUE THREAD

**Issue by rayshih** [FrigoEU/psc-ide-vim#50]
This is what I got for this command `:echo g:psc_ide_suggestions`

```
{'src/Main.purs|8': {'filename': 'src/Main.purs', 'startColumn': 1, 'endColumn': 11, 'startLine': 8, 'replacement': 'im
port Pux (App, CoreEffects, EffModel, noEffects, start)
', 'endLine': 8}, 'src/Main.purs|3': {'filename': 'src/Main.purs', 'startColumn': 1, 'endColumn': 28, 'startLine': 3, '
replacement': 'import Prelude (bind, const, discard, pure, show, ($), (+), (/=), (<>))
', 'endLine': 3}}
```

And for those functions using this information, for example:

https://github.com/FrigoEU/psc-ide-vim/blob/master/ftplugin/purescript_pscide.vim#L537

```
let filename = expand("%:p")
```

It will return full path like: `/Users/rayshih/workspace/purescript-pux-todomvc/src/Main.purs`

So It won't find the suggestion since one is the full path and the other is the relative path.

Does that mean I make a mistake in the configuration?

BTW the version of psc ide server I have is: `0.11.4`

**Comment by paluh** [comment]
@rayshih As @kRITZCREEK has already [pointed out](https://github.com/FrigoEU/psc-ide-vim/issues/47) this is a `purs ide` [issue](https://github.com/purescript/purescript/pull/2867).

Maybe we should make temporary "fix" and change `%:p` to `%` in `PSCIDEapplySuggestion` till next `purescript` release (I'm patching it locally anyway because I can't live without automatic suggestion resolving).

**Comment by rayshih** [comment]
@paluh Thanks for replying promptly. Could you maybe create a branch to include the patch of yours? Because I'm not familiar with vimscript. Thanks!

**Comment by paluh** [comment]
@rayshih [Here](https://github.com/paluh/psc-ide-vim) you go!

**Comment by rayshih** [comment]
@paluh cool!! Thank you!

**Comment by paluh** [comment]
@rayshih I'm also trying to fix/improve `importIdenfier` behavior on my branch, so if you notice any bugs related to this function please let me know.

**Comment by FrigoEU** [comment]
Could you try this again on the brand spanking new release?

**Comment by chexxor** [comment]
I tested FrigoEU/psc-ide-vim:master with PSC-0.11.5 and confirm the applySuggestion command works. It doesn't work on PSC-0.11.4, however, because PSC returns full path to file, not relative path to file. This change is noted in the [PSC-0.11.5 release notes](https://github.com/purescript/purescript/releases/tag/v0.11.5)

A bit sad master branch doesn't work with PSC 0.11.4, but I think this master branch should track PSC latest release. If a psc-ide-vim user wants to use an older version of PSC, then they need to use an older version of psc-ide-vim. We could cut a release/tag of this plugin to match the PSC version it supports, but I'm not sure the rules we'd need to follow to make that work.

**Comment by coot** [comment]
It seems everything works fine now.
